### ISSUE TITLE
Rename project since it uses features beyond Fortran 90

### ISSUE THREAD

**Issue by Beliavsky** [jordan4ibanez/files_f90#1]
I suggest renaming the project to files_modern_fortran since it uses features such as iso_c_binding that were added after the Fortran 90 standard.

**Comment by jordan4ibanez** [comment]
I think this is a wise idea, but all the files end with f90 so it's also a bit nitpicky. Perhaps we could just say in the description the fortran standard is 03+ as a common ground solution?

**Comment by Beliavsky** [comment]
Files using a suffix of .f90 mean that free source form is used, not that the Fortran 90 is adhered to. Maybe call it files_fortran.

**Comment by jordan4ibanez** [comment]
Yeah, so if it's known that freeform is used by the designation that f90 is used, there's no reason to reaname it, all I have to do is say it's fortran 03+

**Comment by jordan4ibanez** [comment]
fixed in 2538ba0
